"use client";

import Link from "next/link";
import { useActionState } from "react";
import { requestResetCode, resetPassword } from "./actions";

export default function ForgotPasswordPage() {
  const [sendState, sendAction, sending] = useActionState(requestResetCode, undefined);
  const [resetState, resetAction, resetting] = useActionState(resetPassword, undefined);
  return <div className="mx-auto max-w-md px-4 py-16"><h1 className="text-2xl font-semibold">找回密码</h1><p className="mt-1 text-sm text-slate-500">使用注册邮箱接收验证码并设置新密码。</p><form action={sendAction} className="mt-8 space-y-3"><label className="block text-sm font-medium">注册邮箱</label><div className="flex gap-2"><input name="email" type="email" required placeholder="请输入注册邮箱" className="min-w-0 flex-1 rounded-lg border border-slate-300 px-3 py-2 outline-none focus:border-slate-900" /><button disabled={sending} className="rounded-lg bg-violet-600 px-4 py-2 text-sm font-medium text-white disabled:opacity-60">{sending ? "发送中" : "发送验证码"}</button></div>{sendState?.error && <p className="text-sm text-rose-600">{sendState.error}</p>}{sendState?.success && <p className="text-sm text-emerald-600">{sendState.success}</p>}</form><form action={resetAction} className="mt-8 space-y-4 border-t border-slate-200 pt-6"><div><label className="block text-sm font-medium">注册邮箱</label><input name="email" type="email" required className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" /></div><div><label className="block text-sm font-medium">6 位验证码</label><input name="code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} required className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 tracking-[0.3em]" /></div><div><label className="block text-sm font-medium">新密码</label><input name="password" type="password" minLength={6} required className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" /><p className="mt-1 text-xs text-slate-400">至少 6 个字符</p></div>{resetState?.error && <p className="rounded-lg bg-rose-50 px-3 py-2 text-sm text-rose-700">{resetState.error}</p>}{resetState?.success && <p className="rounded-lg bg-emerald-50 px-3 py-2 text-sm text-emerald-700">{resetState.success}</p>}<button disabled={resetting} className="w-full rounded-lg bg-slate-900 py-2.5 font-medium text-white disabled:opacity-60">{resetting ? "重置中..." : "重置密码"}</button></form><p className="mt-6 text-center text-sm"><Link href="/login" className="font-medium text-slate-900 underline">返回登录</Link></p></div>;
}
